### PR TITLE
Revert "Update response collection table formatting"

### PR DESCRIPTION
**Pull request by sprshrp**
Reverts salesforce-marketingcloud/SFDC-MC-REST-Style-Guide#48

### CODE REVIEW

**Comment by dougwilson** [comment]
What was the point of merging the change and then reverting it? Without the change, the table is completely broken: https://github.com/salesforce-marketingcloud/SFDC-MC-REST-Style-Guide#envelope

**Comment by dougwilson** [comment]
(You can see the brokenness by looking at the second row in the table)

**Comment by sprshrp** [comment]
A preference for how the file looks in Vim and an ignorance of accepting merges?  It was my impression that @vernak2539 had already committed to master.  Fucking Markdown.  I'll revert back.

**Comment by sprshrp** [comment]
(tomorrow)

**Comment by vernak2539** [comment]
Wait, so you merged it back to the broken part, then are merging my fix again? I understand you want to keep it at 80 or whatever, but to keep it completely broken and hard to figure out?

**Comment by sprshrp** [comment]
@vernak2539 - yeah. not going to keep the broken table. reverting now.

**Comment by vernak2539** [comment]
:+1:

**Pull request merged**
